### ISSUE TITLE
husky_base: Handle encoder travel wraparound in basic_odom_publisher

### ISSUE THREAD

**Issue by mikepurvis** [husky/husky_base#4]
Right now when the encoders wrap around, there's a giant discontinuity for the published pose. This is unacceptable for long-running experiments.

**Comment by pomerlef** [comment]
It worth mentioning that it can also be dangerous if the system is run with any kind of autonomous mode.

**Comment by pomerlef** [comment]
A patched version of dead_reckoning.py can be found here: https://github.com/pomerlef/husky_bringup/blob/rosbuild/nodes/dead_reckoning.py

It is a temporary fix, but avoid the problem to spread in other nodes.

**Comment by paulbovbel** [comment]
Fixed in https://github.com/husky/husky_base/pull/9
