### ISSUE TITLE
Odometry jump at high distances

### ISSUE THREAD

**Issue by tobiasneumann** [husky/husky_base#7]
After long tours the odometry jumps.
Launched with:
<node pkg="husky_base" name="husky_basic_odom" type="basic_odom_publisher" />

You can see the output of "rostopic echo /encoder" in the following two pictures:
![jump1](https://cloud.githubusercontent.com/assets/1560727/4951440/a45fb786-6667-11e4-9875-cf873dad9acb.png)
![jump2](https://cloud.githubusercontent.com/assets/1560727/4951439/a459a5da-6667-11e4-9a54-993193d88748.png)

**Comment by mikepurvis** [comment]
Agree, this is no good, and we plan to fix it for the Indigo release! Presently being tracked in #4.
